// AUTO-GENERATED by scripts/generate_ecommerce_data.py
// Synthetic e-commerce dataset mirroring the notebook schema
// 2,000 transactions across 2023-01-01 .. 2025-12-31

export type Kpis = {
  total_sales: number;
  total_profit: number;
  total_orders: number;
  avg_order_value: number;
  avg_discount: number;
  profit_margin: number;
  total_shipping: number;
  unique_customers: number;
  negative_profit_orders: number;
  yearly: Record<number, { revenue: number; profit: number; orders: number }>;
};

export const kpis: Kpis = {
  "total_sales": 540919.52,
  "total_profit": 84154.06,
  "total_orders": 2000,
  "avg_order_value": 270.46,
  "avg_discount": 8.93,
  "profit_margin": 15.56,
  "total_shipping": 35246.78,
  "unique_customers": 636,
  "negative_profit_orders": 408,
  "yearly": {
    "2023": {
      "revenue": 193320.81,
      "profit": 29877.14,
      "orders": 699
    },
    "2024": {
      "revenue": 179582.04,
      "profit": 27904.33,
      "orders": 652
    },
    "2025": {
      "revenue": 168016.67,
      "profit": 26372.59,
      "orders": 649
    }
  }
};

export const monthlyData = [
  {
    "year_month": "2023-01",
    "label": "Jan 2023",
    "revenue": 14862.62,
    "profit": 1758.34,
    "orders": 46
  },
  {
    "year_month": "2023-02",
    "label": "Feb 2023",
    "revenue": 11841.74,
    "profit": 1931.44,
    "orders": 34
  },
  {
    "year_month": "2023-03",
    "label": "Mar 2023",
    "revenue": 10542.76,
    "profit": 1856.42,
    "orders": 47
  },
  {
    "year_month": "2023-04",
    "label": "Apr 2023",
    "revenue": 13832.59,
    "profit": 2091.14,
    "orders": 57
  },
  {
    "year_month": "2023-05",
    "label": "May 2023",
    "revenue": 17645.33,
    "profit": 2811.77,
    "orders": 47
  },
  {
    "year_month": "2023-06",
    "label": "Jun 2023",
    "revenue": 13397.16,
    "profit": 2107.34,
    "orders": 52
  },
  {
    "year_month": "2023-07",
    "label": "Jul 2023",
    "revenue": 16797.47,
    "profit": 2864.08,
    "orders": 60
  },
  {
    "year_month": "2023-08",
    "label": "Aug 2023",
    "revenue": 11305.94,
    "profit": 1831.6,
    "orders": 48
  },
  {
    "year_month": "2023-09",
    "label": "Sep 2023",
    "revenue": 18068.03,
    "profit": 2908.23,
    "orders": 65
  },
  {
    "year_month": "2023-10",
    "label": "Oct 2023",
    "revenue": 12765.88,
    "profit": 1774.52,
    "orders": 57
  },
  {
    "year_month": "2023-11",
    "label": "Nov 2023",
    "revenue": 25483.06,
    "profit": 4059.26,
    "orders": 87
  },
  {
    "year_month": "2023-12",
    "label": "Dec 2023",
    "revenue": 26778.23,
    "profit": 3883.0,
    "orders": 99
  },
  {
    "year_month": "2024-01",
    "label": "Jan 2024",
    "revenue": 11780.26,
    "profit": 1512.22,
    "orders": 42
  },
  {
    "year_month": "2024-02",
    "label": "Feb 2024",
    "revenue": 7643.11,
    "profit": 982.68,
    "orders": 30
  },
  {
    "year_month": "2024-03",
    "label": "Mar 2024",
    "revenue": 14939.12,
    "profit": 2149.28,
    "orders": 52
  },
  {
    "year_month": "2024-04",
    "label": "Apr 2024",
    "revenue": 14240.52,
    "profit": 2910.35,
    "orders": 44
  },
  {
    "year_month": "2024-05",
    "label": "May 2024",
    "revenue": 10237.96,
    "profit": 1440.1,
    "orders": 44
  },
  {
    "year_month": "2024-06",
    "label": "Jun 2024",
    "revenue": 17790.71,
    "profit": 3143.17,
    "orders": 64
  },
  {
    "year_month": "2024-07",
    "label": "Jul 2024",
    "revenue": 15777.52,
    "profit": 2497.74,
    "orders": 62
  },
  {
    "year_month": "2024-08",
    "label": "Aug 2024",
    "revenue": 9777.3,
    "profit": 1549.52,
    "orders": 45
  },
  {
    "year_month": "2024-09",
    "label": "Sep 2024",
    "revenue": 14546.18,
    "profit": 2219.0,
    "orders": 60
  },
  {
    "year_month": "2024-10",
    "label": "Oct 2024",
    "revenue": 22153.67,
    "profit": 3506.65,
    "orders": 62
  },
  {
    "year_month": "2024-11",
    "label": "Nov 2024",
    "revenue": 17584.55,
    "profit": 2722.59,
    "orders": 70
  },
  {
    "year_month": "2024-12",
    "label": "Dec 2024",
    "revenue": 23111.14,
    "profit": 3271.03,
    "orders": 77
  },
  {
    "year_month": "2025-01",
    "label": "Jan 2025",
    "revenue": 8578.79,
    "profit": 1066.57,
    "orders": 28
  },
  {
    "year_month": "2025-02",
    "label": "Feb 2025",
    "revenue": 12651.51,
    "profit": 1726.73,
    "orders": 47
  },
  {
    "year_month": "2025-03",
    "label": "Mar 2025",
    "revenue": 9462.91,
    "profit": 1593.95,
    "orders": 48
  },
  {
    "year_month": "2025-04",
    "label": "Apr 2025",
    "revenue": 16680.62,
    "profit": 3126.32,
    "orders": 58
  },
  {
    "year_month": "2025-05",
    "label": "May 2025",
    "revenue": 13483.09,
    "profit": 1893.96,
    "orders": 50
  },
  {
    "year_month": "2025-06",
    "label": "Jun 2025",
    "revenue": 15087.7,
    "profit": 2057.62,
    "orders": 52
  },
  {
    "year_month": "2025-07",
    "label": "Jul 2025",
    "revenue": 10669.14,
    "profit": 1507.34,
    "orders": 50
  },
  {
    "year_month": "2025-08",
    "label": "Aug 2025",
    "revenue": 10065.6,
    "profit": 1168.62,
    "orders": 49
  },
  {
    "year_month": "2025-09",
    "label": "Sep 2025",
    "revenue": 14758.49,
    "profit": 2371.27,
    "orders": 55
  },
  {
    "year_month": "2025-10",
    "label": "Oct 2025",
    "revenue": 19020.77,
    "profit": 3835.18,
    "orders": 65
  },
  {
    "year_month": "2025-11",
    "label": "Nov 2025",
    "revenue": 15468.88,
    "profit": 2605.4,
    "orders": 59
  },
  {
    "year_month": "2025-12",
    "label": "Dec 2025",
    "revenue": 22089.17,
    "profit": 3419.63,
    "orders": 88
  }
];

export const yoyData = [
  {
    "year": 2023,
    "revenue": 193320.81,
    "profit": 29877.14,
    "orders": 699
  },
  {
    "year": 2024,
    "revenue": 179582.04,
    "profit": 27904.33,
    "orders": 652
  },
  {
    "year": 2025,
    "revenue": 168016.67,
    "profit": 26372.59,
    "orders": 649
  }
];

export const heatmapData = [
  {
    "year": 2023,
    "quarter": "Q1",
    "revenue": 37247.12
  },
  {
    "year": 2023,
    "quarter": "Q2",
    "revenue": 44875.08
  },
  {
    "year": 2023,
    "quarter": "Q3",
    "revenue": 46171.44
  },
  {
    "year": 2023,
    "quarter": "Q4",
    "revenue": 65027.17
  },
  {
    "year": 2024,
    "quarter": "Q1",
    "revenue": 34362.49
  },
  {
    "year": 2024,
    "quarter": "Q2",
    "revenue": 42269.19
  },
  {
    "year": 2024,
    "quarter": "Q3",
    "revenue": 40101.0
  },
  {
    "year": 2024,
    "quarter": "Q4",
    "revenue": 62849.36
  },
  {
    "year": 2025,
    "quarter": "Q1",
    "revenue": 30693.21
  },
  {
    "year": 2025,
    "quarter": "Q2",
    "revenue": 45251.41
  },
  {
    "year": 2025,
    "quarter": "Q3",
    "revenue": 35493.23
  },
  {
    "year": 2025,
    "quarter": "Q4",
    "revenue": 56578.82
  }
];

export const regionData = [
  {
    "region": "North America",
    "revenue": 196700.88,
    "profit": 34522.66,
    "orders": 686,
    "avg_order": 286.74,
    "avg_shipping": 13.33,
    "profit_margin": 17.6
  },
  {
    "region": "Europe",
    "revenue": 145882.52,
    "profit": 22399.92,
    "orders": 561,
    "avg_order": 260.04,
    "avg_shipping": 16.77,
    "profit_margin": 15.4
  },
  {
    "region": "Asia Pacific",
    "revenue": 125461.1,
    "profit": 18773.07,
    "orders": 445,
    "avg_order": 281.94,
    "avg_shipping": 19.42,
    "profit_margin": 15.0
  },
  {
    "region": "Latin America",
    "revenue": 40378.09,
    "profit": 5671.23,
    "orders": 169,
    "avg_order": 238.92,
    "avg_shipping": 23.08,
    "profit_margin": 14.0
  },
  {
    "region": "Middle East & Africa",
    "revenue": 32496.93,
    "profit": 2787.18,
    "orders": 139,
    "avg_order": 233.79,
    "avg_shipping": 29.86,
    "profit_margin": 8.6
  }
];

export const countryData = [
  {
    "country": "Canada",
    "region": "North America",
    "revenue": 74965.31,
    "profit": 13194.03,
    "orders": 252
  },
  {
    "country": "Mexico",
    "region": "North America",
    "revenue": 62732.45,
    "profit": 11036.76,
    "orders": 217
  },
  {
    "country": "United States",
    "region": "North America",
    "revenue": 59003.12,
    "profit": 10291.87,
    "orders": 217
  },
  {
    "country": "Netherlands",
    "region": "Europe",
    "revenue": 25890.35,
    "profit": 3851.1,
    "orders": 100
  },
  {
    "country": "France",
    "region": "Europe",
    "revenue": 25534.72,
    "profit": 4621.93,
    "orders": 89
  },
  {
    "country": "United Kingdom",
    "region": "Europe",
    "revenue": 25491.85,
    "profit": 3411.54,
    "orders": 94
  },
  {
    "country": "Spain",
    "region": "Europe",
    "revenue": 24948.9,
    "profit": 4057.75,
    "orders": 85
  },
  {
    "country": "Italy",
    "region": "Europe",
    "revenue": 24662.78,
    "profit": 3555.33,
    "orders": 108
  },
  {
    "country": "Japan",
    "region": "Asia Pacific",
    "revenue": 22566.16,
    "profit": 3149.87,
    "orders": 79
  },
  {
    "country": "China",
    "region": "Asia Pacific",
    "revenue": 22221.8,
    "profit": 2890.07,
    "orders": 75
  },
  {
    "country": "India",
    "region": "Asia Pacific",
    "revenue": 21686.25,
    "profit": 3267.71,
    "orders": 72
  },
  {
    "country": "Singapore",
    "region": "Asia Pacific",
    "revenue": 20446.58,
    "profit": 3309.51,
    "orders": 72
  },
  {
    "country": "South Korea",
    "region": "Asia Pacific",
    "revenue": 19753.87,
    "profit": 3142.6,
    "orders": 78
  },
  {
    "country": "Germany",
    "region": "Europe",
    "revenue": 19353.92,
    "profit": 2902.27,
    "orders": 85
  },
  {
    "country": "Australia",
    "region": "Asia Pacific",
    "revenue": 18786.44,
    "profit": 3013.31,
    "orders": 69
  },
  {
    "country": "Brazil",
    "region": "Latin America",
    "revenue": 14974.17,
    "profit": 1943.58,
    "orders": 59
  },
  {
    "country": "Argentina",
    "region": "Latin America",
    "revenue": 13413.2,
    "profit": 1995.22,
    "orders": 61
  },
  {
    "country": "Chile",
    "region": "Latin America",
    "revenue": 11990.72,
    "profit": 1732.43,
    "orders": 49
  },
  {
    "country": "Saudi Arabia",
    "region": "Middle East & Africa",
    "revenue": 9631.97,
    "profit": 961.35,
    "orders": 34
  },
  {
    "country": "South Africa",
    "region": "Middle East & Africa",
    "revenue": 8398.27,
    "profit": 656.91,
    "orders": 36
  },
  {
    "country": "United Arab Emirates",
    "region": "Middle East & Africa",
    "revenue": 7763.38,
    "profit": 703.18,
    "orders": 35
  },
  {
    "country": "Turkey",
    "region": "Middle East & Africa",
    "revenue": 6703.31,
    "profit": 465.74,
    "orders": 34
  }
];

export const categoryData = [
  {
    "category": "Electronics",
    "revenue": 334085.78,
    "profit": 34155.22,
    "orders": 780,
    "units": 1603,
    "avg_price": 231.1,
    "avg_discount": 9.22,
    "profit_margin": 10.2
  },
  {
    "category": "Clothing",
    "revenue": 131326.88,
    "profit": 37743.27,
    "orders": 564,
    "units": 1110,
    "avg_price": 129.18,
    "avg_discount": 8.6,
    "profit_margin": 28.7
  },
  {
    "category": "Home & Kitchen",
    "revenue": 62569.82,
    "profit": 10081.11,
    "orders": 403,
    "units": 818,
    "avg_price": 85.23,
    "avg_discount": 8.68,
    "profit_margin": 16.1
  },
  {
    "category": "Books",
    "revenue": 12937.04,
    "profit": 2174.46,
    "orders": 253,
    "units": 523,
    "avg_price": 27.33,
    "avg_discount": 9.21,
    "profit_margin": 16.8
  }
];

export const topProductsData = [
  {
    "product": "Nimbus Tablet 10.4",
    "category": "Electronics",
    "revenue": 94983.95,
    "profit": 10325.46,
    "units": 252,
    "orders": 131
  },
  {
    "product": "Horizon 4K Action Camera",
    "category": "Electronics",
    "revenue": 65457.47,
    "profit": 7715.42,
    "units": 218,
    "orders": 101
  },
  {
    "product": "Vertex Stainless Smartwatch",
    "category": "Electronics",
    "revenue": 58397.72,
    "profit": 6258.44,
    "units": 257,
    "orders": 126
  },
  {
    "product": "Alpine Down Jacket",
    "category": "Clothing",
    "revenue": 47875.73,
    "profit": 15636.56,
    "units": 183,
    "orders": 92
  },
  {
    "product": "Aurora Wireless Earbuds Pro",
    "category": "Electronics",
    "revenue": 41553.38,
    "profit": 4525.48,
    "units": 226,
    "orders": 114
  },
  {
    "product": "Pulse Fitness Tracker X",
    "category": "Electronics",
    "revenue": 32072.21,
    "profit": 3425.45,
    "units": 217,
    "orders": 100
  },
  {
    "product": "Verde Ceramic Cookware Set",
    "category": "Home & Kitchen",
    "revenue": 24864.86,
    "profit": 5352.69,
    "units": 127,
    "orders": 65
  },
  {
    "product": "Vortex Running Shoes",
    "category": "Clothing",
    "revenue": 21942.34,
    "profit": 6039.71,
    "units": 219,
    "orders": 113
  },
  {
    "product": "Echo Bluetooth Speaker",
    "category": "Electronics",
    "revenue": 21534.77,
    "profit": 1418.65,
    "units": 184,
    "orders": 89
  },
  {
    "product": "Heritage Denim Jacket",
    "category": "Clothing",
    "revenue": 20951.92,
    "profit": 6126.37,
    "units": 166,
    "orders": 85
  }
];

export const segmentData = [
  {
    "segment": "Consumer",
    "revenue": 313773.47,
    "profit": 54875.9,
    "orders": 1097,
    "avg_order_value": 286.03,
    "avg_discount": 6.67,
    "profit_margin": 17.5
  },
  {
    "segment": "Corporate",
    "revenue": 153276.06,
    "profit": 18100.41,
    "orders": 622,
    "avg_order_value": 246.42,
    "avg_discount": 12.92,
    "profit_margin": 11.8
  },
  {
    "segment": "Home Office",
    "revenue": 73869.99,
    "profit": 11177.75,
    "orders": 281,
    "avg_order_value": 262.88,
    "avg_discount": 8.95,
    "profit_margin": 15.1
  }
];

export const segmentCategoryData = [
  {
    "segment": "Consumer",
    "values": {
      "Electronics": 194856.94,
      "Clothing": 76604.6,
      "Home & Kitchen": 35326.68,
      "Books": 6985.25
    }
  },
  {
    "segment": "Corporate",
    "values": {
      "Electronics": 91746.82,
      "Clothing": 39628.92,
      "Home & Kitchen": 18286.47,
      "Books": 3613.85
    }
  },
  {
    "segment": "Home Office",
    "values": {
      "Electronics": 47482.02,
      "Clothing": 15093.36,
      "Home & Kitchen": 8956.67,
      "Books": 2337.94
    }
  }
];

export const discountScatter = [
  {
    "discount": 14.5,
    "profit_margin": 5.6,
    "total_sales": 384.32,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 7.6,
    "profit_margin": 25.85,
    "total_sales": 218.06,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 22.1,
    "profit_margin": -43.7,
    "total_sales": 21.03,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 12.5,
    "profit_margin": 27.21,
    "total_sales": 69.98,
    "category": "Books",
    "product": "The Pragmatic Programmer"
  },
  {
    "discount": 4.9,
    "profit_margin": -7.12,
    "total_sales": 37.94,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 16.9,
    "profit_margin": -1.98,
    "total_sales": 206.92,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 22.3,
    "profit_margin": 12.9,
    "total_sales": 108.0,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 22.2,
    "profit_margin": -17.69,
    "total_sales": 49.79,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 0.0,
    "profit_margin": 31.49,
    "total_sales": 192.0,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 0.0,
    "profit_margin": 20.39,
    "total_sales": 747.0,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 9.2,
    "profit_margin": 42.1,
    "total_sales": 122.53,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 22.1,
    "profit_margin": 13.68,
    "total_sales": 99.71,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 20.8,
    "profit_margin": -4.05,
    "total_sales": 260.57,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 11.9,
    "profit_margin": 0.09,
    "total_sales": 35.23,
    "category": "Books",
    "product": "The Pragmatic Programmer"
  },
  {
    "discount": 9.9,
    "profit_margin": -0.09,
    "total_sales": 179.3,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 9.2,
    "profit_margin": 18.09,
    "total_sales": 36.31,
    "category": "Books",
    "product": "The Pragmatic Programmer"
  },
  {
    "discount": 5.4,
    "profit_margin": 25.45,
    "total_sales": 223.26,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 4.5,
    "profit_margin": 8.5,
    "total_sales": 151.84,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 5.6,
    "profit_margin": 21.57,
    "total_sales": 102.9,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 8.8,
    "profit_margin": 31.43,
    "total_sales": 263.57,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 11.9,
    "profit_margin": 5.73,
    "total_sales": 579.7,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 9.8,
    "profit_margin": 4.76,
    "total_sales": 224.6,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 3.7,
    "profit_margin": 31.2,
    "total_sales": 119.89,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 18.0,
    "profit_margin": 1.56,
    "total_sales": 408.36,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 0.0,
    "profit_margin": -21.67,
    "total_sales": 27.0,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 8.5,
    "profit_margin": 1.01,
    "total_sales": 62.22,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 8.1,
    "profit_margin": 32.73,
    "total_sales": 500.86,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 0.0,
    "profit_margin": 30.56,
    "total_sales": 45.0,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 1.8,
    "profit_margin": 34.68,
    "total_sales": 244.52,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 0.0,
    "profit_margin": 25.98,
    "total_sales": 238.0,
    "category": "Home & Kitchen",
    "product": "Cozy Weighted Blanket"
  },
  {
    "discount": 0.0,
    "profit_margin": 10.23,
    "total_sales": 64.0,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 0.0,
    "profit_margin": 28.8,
    "total_sales": 218.0,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 7.1,
    "profit_margin": 41.18,
    "total_sales": 148.6,
    "category": "Books",
    "product": "The Pragmatic Programmer"
  },
  {
    "discount": 0.0,
    "profit_margin": -12.13,
    "total_sales": 22.5,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 5.7,
    "profit_margin": 9.53,
    "total_sales": 375.31,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 0.0,
    "profit_margin": 17.97,
    "total_sales": 747.0,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 3.5,
    "profit_margin": 18.18,
    "total_sales": 1587.42,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 0.0,
    "profit_margin": 15.77,
    "total_sales": 329.0,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 8.8,
    "profit_margin": 30.09,
    "total_sales": 397.63,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 10.9,
    "profit_margin": 2.9,
    "total_sales": 114.94,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 2.2,
    "profit_margin": 31.43,
    "total_sales": 121.76,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 7.8,
    "profit_margin": 12.74,
    "total_sales": 772.64,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 5.7,
    "profit_margin": -2.63,
    "total_sales": 37.63,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 13.9,
    "profit_margin": -10.65,
    "total_sales": 46.48,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 0.0,
    "profit_margin": 20.32,
    "total_sales": 838.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 6.7,
    "profit_margin": -1.71,
    "total_sales": 25.18,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 20.5,
    "profit_margin": 6.44,
    "total_sales": 108.12,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 10.8,
    "profit_margin": -12.18,
    "total_sales": 80.19,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 8.3,
    "profit_margin": 32.55,
    "total_sales": 265.01,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 0.0,
    "profit_margin": 18.09,
    "total_sales": 419.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 7.2,
    "profit_margin": 29.52,
    "total_sales": 100.19,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 0.0,
    "profit_margin": 20.59,
    "total_sales": 796.0,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 14.9,
    "profit_margin": 3.6,
    "total_sales": 423.8,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 13.7,
    "profit_margin": 3.54,
    "total_sales": 171.74,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 7.7,
    "profit_margin": 15.44,
    "total_sales": 74.76,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 23.7,
    "profit_margin": -5.62,
    "total_sales": 502.05,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 3.4,
    "profit_margin": 17.34,
    "total_sales": 721.6,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 23.6,
    "profit_margin": 17.67,
    "total_sales": 212.39,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 0.0,
    "profit_margin": 8.58,
    "total_sales": 22.5,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 11.9,
    "profit_margin": -30.52,
    "total_sales": 29.95,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 13.6,
    "profit_margin": 1.37,
    "total_sales": 55.3,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 5.9,
    "profit_margin": 14.5,
    "total_sales": 60.22,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 4.1,
    "profit_margin": -1.22,
    "total_sales": 61.38,
    "category": "Home & Kitchen",
    "product": "Nimbus Memory Foam Pillow"
  },
  {
    "discount": 3.9,
    "profit_margin": 16.37,
    "total_sales": 948.51,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 0.0,
    "profit_margin": 20.16,
    "total_sales": 838.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 19.4,
    "profit_margin": 8.94,
    "total_sales": 43.51,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 20.9,
    "profit_margin": 6.86,
    "total_sales": 98.48,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 17.1,
    "profit_margin": -8.09,
    "total_sales": 66.15,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 14.2,
    "profit_margin": 5.67,
    "total_sales": 359.5,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 21.6,
    "profit_margin": -8.21,
    "total_sales": 257.94,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 14.8,
    "profit_margin": 3.47,
    "total_sales": 40.9,
    "category": "Books",
    "product": "Atomic Habits (Hardcover)"
  },
  {
    "discount": 5.4,
    "profit_margin": 15.65,
    "total_sales": 706.66,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 6.3,
    "profit_margin": 2.9,
    "total_sales": 168.47,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 19.6,
    "profit_margin": -96.09,
    "total_sales": 27.34,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 13.7,
    "profit_margin": 24.59,
    "total_sales": 77.67,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 5.1,
    "profit_margin": 14.35,
    "total_sales": 489.68,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 10.9,
    "profit_margin": 10.69,
    "total_sales": 1119.99,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 2.7,
    "profit_margin": 34.26,
    "total_sales": 424.23,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 3.5,
    "profit_margin": 17.44,
    "total_sales": 961.14,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 21.1,
    "profit_margin": -13.36,
    "total_sales": 203.56,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 8.4,
    "profit_margin": 9.03,
    "total_sales": 301.36,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 5.1,
    "profit_margin": 16.16,
    "total_sales": 936.66,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 5.5,
    "profit_margin": 0.44,
    "total_sales": 121.91,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 11.7,
    "profit_margin": 28.22,
    "total_sales": 288.74,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 5.8,
    "profit_margin": 4.25,
    "total_sales": 64.06,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 9.0,
    "profit_margin": 13.2,
    "total_sales": 123.76,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 13.0,
    "profit_margin": 12.31,
    "total_sales": 129.19,
    "category": "Home & Kitchen",
    "product": "Lumen Aroma Diffuser"
  },
  {
    "discount": 0.0,
    "profit_margin": 18.58,
    "total_sales": 419.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 5.7,
    "profit_margin": 33.0,
    "total_sales": 272.53,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 0.0,
    "profit_margin": 17.97,
    "total_sales": 419.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 0.0,
    "profit_margin": 18.55,
    "total_sales": 658.0,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 19.5,
    "profit_margin": 13.68,
    "total_sales": 111.89,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 5.2,
    "profit_margin": -45.45,
    "total_sales": 25.59,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 5.1,
    "profit_margin": 9.71,
    "total_sales": 129.06,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 11.2,
    "profit_margin": -5.78,
    "total_sales": 105.67,
    "category": "Home & Kitchen",
    "product": "Cozy Weighted Blanket"
  },
  {
    "discount": 9.7,
    "profit_margin": 15.66,
    "total_sales": 144.12,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 0.0,
    "profit_margin": 39.08,
    "total_sales": 578.0,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 1.5,
    "profit_margin": 37.82,
    "total_sales": 490.53,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 8.1,
    "profit_margin": 17.56,
    "total_sales": 156.23,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 17.7,
    "profit_margin": 3.79,
    "total_sales": 1379.35,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 12.2,
    "profit_margin": 7.09,
    "total_sales": 367.88,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 15.3,
    "profit_margin": 16.2,
    "total_sales": 105.45,
    "category": "Clothing",
    "product": "Summit Trekking Backpack"
  },
  {
    "discount": 13.3,
    "profit_margin": -48.58,
    "total_sales": 29.48,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 0.0,
    "profit_margin": 14.3,
    "total_sales": 419.0,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 2.2,
    "profit_margin": -12.31,
    "total_sales": 23.47,
    "category": "Books",
    "product": "Atomic Habits (Hardcover)"
  },
  {
    "discount": 5.9,
    "profit_margin": 29.45,
    "total_sales": 180.67,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 11.5,
    "profit_margin": 6.88,
    "total_sales": 370.81,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 13.4,
    "profit_margin": 8.24,
    "total_sales": 103.05,
    "category": "Home & Kitchen",
    "product": "Cozy Weighted Blanket"
  },
  {
    "discount": 14.5,
    "profit_margin": 5.92,
    "total_sales": 425.79,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 5.4,
    "profit_margin": 5.91,
    "total_sales": 170.09,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 14.4,
    "profit_margin": -0.06,
    "total_sales": 170.34,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 4.6,
    "profit_margin": 28.93,
    "total_sales": 207.97,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 19.0,
    "profit_margin": 2.23,
    "total_sales": 1018.17,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 11.9,
    "profit_margin": 4.42,
    "total_sales": 280.16,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 13.8,
    "profit_margin": -9.17,
    "total_sales": 34.47,
    "category": "Books",
    "product": "The Pragmatic Programmer"
  },
  {
    "discount": 6.0,
    "profit_margin": 13.16,
    "total_sales": 422.53,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 14.3,
    "profit_margin": 2.33,
    "total_sales": 331.66,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 12.9,
    "profit_margin": 6.5,
    "total_sales": 415.47,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 18.6,
    "profit_margin": 1.8,
    "total_sales": 682.13,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 2.7,
    "profit_margin": 32.11,
    "total_sales": 135.25,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 11.3,
    "profit_margin": 3.63,
    "total_sales": 47.9,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 14.7,
    "profit_margin": 11.94,
    "total_sales": 118.57,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 14.0,
    "profit_margin": 3.35,
    "total_sales": 282.94,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 1.7,
    "profit_margin": 32.78,
    "total_sales": 115.99,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 15.5,
    "profit_margin": 4.32,
    "total_sales": 420.81,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 0.0,
    "profit_margin": 24.4,
    "total_sales": 109.0,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 17.4,
    "profit_margin": -12.12,
    "total_sales": 74.26,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 12.3,
    "profit_margin": -35.07,
    "total_sales": 19.73,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 0.1,
    "profit_margin": 29.65,
    "total_sales": 108.89,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 8.2,
    "profit_margin": 12.4,
    "total_sales": 592.11,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 12.4,
    "profit_margin": 4.89,
    "total_sales": 56.06,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 4.3,
    "profit_margin": 37.33,
    "total_sales": 532.09,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 6.8,
    "profit_margin": -1.16,
    "total_sales": 54.99,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 6.4,
    "profit_margin": 39.36,
    "total_sales": 126.36,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 6.5,
    "profit_margin": 32.73,
    "total_sales": 270.21,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 8.0,
    "profit_margin": 31.44,
    "total_sales": 265.88,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 0.0,
    "profit_margin": 27.15,
    "total_sales": 109.0,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 7.8,
    "profit_margin": 12.59,
    "total_sales": 606.68,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 11.6,
    "profit_margin": 15.29,
    "total_sales": 193.6,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 10.3,
    "profit_margin": -5.21,
    "total_sales": 80.64,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 18.1,
    "profit_margin": 23.88,
    "total_sales": 236.69,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 13.5,
    "profit_margin": 4.38,
    "total_sales": 311.05,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 6.4,
    "profit_margin": 21.85,
    "total_sales": 179.71,
    "category": "Home & Kitchen",
    "product": "Nimbus Memory Foam Pillow"
  },
  {
    "discount": 19.5,
    "profit_margin": 15.57,
    "total_sales": 705.18,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 11.2,
    "profit_margin": 3.4,
    "total_sales": 56.83,
    "category": "Home & Kitchen",
    "product": "Nimbus Memory Foam Pillow"
  },
  {
    "discount": 10.9,
    "profit_margin": 9.72,
    "total_sales": 106.03,
    "category": "Home & Kitchen",
    "product": "Cozy Weighted Blanket"
  },
  {
    "discount": 15.1,
    "profit_margin": 3.41,
    "total_sales": 422.8,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 11.2,
    "profit_margin": 6.57,
    "total_sales": 47.93,
    "category": "Books",
    "product": "The Lean Startup"
  },
  {
    "discount": 5.2,
    "profit_margin": 35.68,
    "total_sales": 516.66,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 13.4,
    "profit_margin": 23.43,
    "total_sales": 102.19,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 0.6,
    "profit_margin": 10.26,
    "total_sales": 158.05,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 19.2,
    "profit_margin": 12.56,
    "total_sales": 353.9,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 6.2,
    "profit_margin": 10.56,
    "total_sales": 298.28,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 5.8,
    "profit_margin": 11.28,
    "total_sales": 60.29,
    "category": "Home & Kitchen",
    "product": "Nimbus Memory Foam Pillow"
  },
  {
    "discount": 17.0,
    "profit_margin": -28.81,
    "total_sales": 48.97,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 8.4,
    "profit_margin": 9.77,
    "total_sales": 364.57,
    "category": "Electronics",
    "product": "Aurora Wireless Earbuds Pro"
  },
  {
    "discount": 13.3,
    "profit_margin": 17.69,
    "total_sales": 166.46,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 5.4,
    "profit_margin": 28.16,
    "total_sales": 103.11,
    "category": "Clothing",
    "product": "Vortex Running Shoes"
  },
  {
    "discount": 5.6,
    "profit_margin": -24.95,
    "total_sales": 21.24,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 13.9,
    "profit_margin": 28.1,
    "total_sales": 497.66,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 14.4,
    "profit_margin": -30.58,
    "total_sales": 29.1,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 19.4,
    "profit_margin": -3.54,
    "total_sales": 154.75,
    "category": "Home & Kitchen",
    "product": "Nimbus Memory Foam Pillow"
  },
  {
    "discount": 12.2,
    "profit_margin": -30.72,
    "total_sales": 29.85,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 2.6,
    "profit_margin": 29.57,
    "total_sales": 639.92,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 13.5,
    "profit_margin": 5.94,
    "total_sales": 311.05,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 7.1,
    "profit_margin": 14.17,
    "total_sales": 916.92,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 1.6,
    "profit_margin": 15.36,
    "total_sales": 44.28,
    "category": "Books",
    "product": "Sapiens: A Brief History"
  },
  {
    "discount": 24.5,
    "profit_margin": -5.13,
    "total_sales": 751.98,
    "category": "Electronics",
    "product": "Vertex Stainless Smartwatch"
  },
  {
    "discount": 13.9,
    "profit_margin": -4.28,
    "total_sales": 111.07,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 10.4,
    "profit_margin": 23.49,
    "total_sales": 392.45,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 9.1,
    "profit_margin": 4.13,
    "total_sales": 234.52,
    "category": "Electronics",
    "product": "Echo Bluetooth Speaker"
  },
  {
    "discount": 9.4,
    "profit_margin": -5.06,
    "total_sales": 30.8,
    "category": "Home & Kitchen",
    "product": "Olive Wood Cutting Board"
  },
  {
    "discount": 0.0,
    "profit_margin": 33.9,
    "total_sales": 177.0,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 2.8,
    "profit_margin": 32.21,
    "total_sales": 270.22,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 20.2,
    "profit_margin": -6.34,
    "total_sales": 262.54,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 7.7,
    "profit_margin": 9.74,
    "total_sales": 386.74,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 7.0,
    "profit_margin": 36.13,
    "total_sales": 1343.85,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 5.3,
    "profit_margin": 15.54,
    "total_sales": 793.59,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 7.8,
    "profit_margin": 10.35,
    "total_sales": 54.4,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 18.6,
    "profit_margin": -23.18,
    "total_sales": 19.54,
    "category": "Books",
    "product": "Atomic Habits (Hardcover)"
  },
  {
    "discount": 1.9,
    "profit_margin": 7.02,
    "total_sales": 88.19,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 7.5,
    "profit_margin": 33.69,
    "total_sales": 534.65,
    "category": "Clothing",
    "product": "Alpine Down Jacket"
  },
  {
    "discount": 21.1,
    "profit_margin": 11.79,
    "total_sales": 109.67,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 2.4,
    "profit_margin": 14.42,
    "total_sales": 321.1,
    "category": "Electronics",
    "product": "Horizon 4K Action Camera"
  },
  {
    "discount": 4.6,
    "profit_margin": -2.93,
    "total_sales": 61.06,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 3.1,
    "profit_margin": 8.4,
    "total_sales": 174.23,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 0.0,
    "profit_margin": 17.25,
    "total_sales": 269.7,
    "category": "Electronics",
    "product": "Lumina Smart LED Lamp"
  },
  {
    "discount": 10.3,
    "profit_margin": 21.0,
    "total_sales": 196.44,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 6.3,
    "profit_margin": 8.36,
    "total_sales": 74.77,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 15.1,
    "profit_margin": 21.93,
    "total_sales": 118.01,
    "category": "Clothing",
    "product": "Heritage Denim Jacket"
  },
  {
    "discount": 0.0,
    "profit_margin": 12.34,
    "total_sales": 159.0,
    "category": "Electronics",
    "product": "Pulse Fitness Tracker X"
  },
  {
    "discount": 9.0,
    "profit_margin": 28.88,
    "total_sales": 49.14,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 24.3,
    "profit_margin": 11.87,
    "total_sales": 178.65,
    "category": "Clothing",
    "product": "Studio Yoga Leggings"
  },
  {
    "discount": 2.0,
    "profit_margin": 19.75,
    "total_sales": 2053.1,
    "category": "Electronics",
    "product": "Nimbus Tablet 10.4"
  },
  {
    "discount": 6.4,
    "profit_margin": -9.99,
    "total_sales": 37.35,
    "category": "Home & Kitchen",
    "product": "Cascade Insulated Bottle"
  },
  {
    "discount": 12.7,
    "profit_margin": 14.09,
    "total_sales": 191.19,
    "category": "Home & Kitchen",
    "product": "Verde Ceramic Cookware Set"
  },
  {
    "discount": 13.7,
    "profit_margin": -5.58,
    "total_sales": 23.3,
    "category": "Books",
    "product": "Deep Work"
  },
  {
    "discount": 14.2,
    "profit_margin": -4.55,
    "total_sales": 54.91,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 0.0,
    "profit_margin": 28.65,
    "total_sales": 128.0,
    "category": "Clothing",
    "product": "Coastline Linen Shirt"
  },
  {
    "discount": 13.8,
    "profit_margin": -16.17,
    "total_sales": 42.67,
    "category": "Home & Kitchen",
    "product": "Lumen Aroma Diffuser"
  }
];

export const discountRangeData = [
  {
    "range": "No Discount",
    "orders": 279,
    "avg_revenue": 288.08,
    "avg_profit": 67.4,
    "avg_margin": 19.81
  },
  {
    "range": "1-10%",
    "orders": 861,
    "avg_revenue": 283.82,
    "avg_profit": 52.87,
    "avg_margin": 13.75
  },
  {
    "range": "11-20%",
    "orders": 736,
    "avg_revenue": 252.54,
    "avg_profit": 25.92,
    "avg_margin": 5.25
  },
  {
    "range": "21-35%",
    "orders": 124,
    "avg_revenue": 244.43,
    "avg_profit": 6.11,
    "avg_margin": -3.73
  }
];

export const paymentData = [
  {
    "method": "Credit Card",
    "orders": 1070,
    "revenue": 294619.24,
    "share": 53.5,
    "avg_order": 275.35
  },
  {
    "method": "PayPal",
    "orders": 514,
    "revenue": 136680.68,
    "share": 25.7,
    "avg_order": 265.92
  },
  {
    "method": "Bank Transfer",
    "orders": 245,
    "revenue": 64117.88,
    "share": 12.2,
    "avg_order": 261.71
  },
  {
    "method": "Debit Card",
    "orders": 171,
    "revenue": 45501.72,
    "share": 8.6,
    "avg_order": 266.09
  }
];

export const shippingData = [
  {
    "region": "North America",
    "avg_shipping": 13.33,
    "profit_margin": 17.6
  },
  {
    "region": "Europe",
    "avg_shipping": 16.77,
    "profit_margin": 15.4
  },
  {
    "region": "Asia Pacific",
    "avg_shipping": 19.42,
    "profit_margin": 15.0
  },
  {
    "region": "Latin America",
    "avg_shipping": 23.08,
    "profit_margin": 14.0
  },
  {
    "region": "Middle East & Africa",
    "avg_shipping": 29.86,
    "profit_margin": 8.6
  }
];

export const correlationMatrix = [
  {
    "feature": "Quantity",
    "Quantity": 1.0,
    "Unit_Price": -0.01,
    "Discount_Percent": -0.03,
    "Total_Sales": 0.54,
    "Shipping_Cost": -0.03,
    "Profit": 0.55,
    "Profit_Margin": 0.41
  },
  {
    "feature": "Unit_Price",
    "Quantity": -0.01,
    "Unit_Price": 1.0,
    "Discount_Percent": 0.04,
    "Total_Sales": 0.71,
    "Shipping_Cost": -0.01,
    "Profit": 0.44,
    "Profit_Margin": 0.18
  },
  {
    "feature": "Discount_Percent",
    "Quantity": -0.03,
    "Unit_Price": 0.04,
    "Discount_Percent": 1.0,
    "Total_Sales": -0.07,
    "Shipping_Cost": -0.01,
    "Profit": -0.3,
    "Profit_Margin": -0.38
  },
  {
    "feature": "Total_Sales",
    "Quantity": 0.54,
    "Unit_Price": 0.71,
    "Discount_Percent": -0.07,
    "Total_Sales": 1.0,
    "Shipping_Cost": -0.04,
    "Profit": 0.79,
    "Profit_Margin": 0.28
  },
  {
    "feature": "Shipping_Cost",
    "Quantity": -0.03,
    "Unit_Price": -0.01,
    "Discount_Percent": -0.01,
    "Total_Sales": -0.04,
    "Shipping_Cost": 1.0,
    "Profit": -0.12,
    "Profit_Margin": -0.27
  },
  {
    "feature": "Profit",
    "Quantity": 0.55,
    "Unit_Price": 0.44,
    "Discount_Percent": -0.3,
    "Total_Sales": 0.79,
    "Shipping_Cost": -0.12,
    "Profit": 1.0,
    "Profit_Margin": 0.55
  },
  {
    "feature": "Profit_Margin",
    "Quantity": 0.41,
    "Unit_Price": 0.18,
    "Discount_Percent": -0.38,
    "Total_Sales": 0.28,
    "Shipping_Cost": -0.27,
    "Profit": 0.55,
    "Profit_Margin": 1.0
  }
];

export const correlationFeatures = [
  "Quantity",
  "Unit_Price",
  "Discount_Percent",
  "Total_Sales",
  "Shipping_Cost",
  "Profit",
  "Profit_Margin"
];

export const dowData = [
  {
    "day": "Monday",
    "orders": 318,
    "avg_revenue": 269.97
  },
  {
    "day": "Tuesday",
    "orders": 267,
    "avg_revenue": 276.59
  },
  {
    "day": "Wednesday",
    "orders": 296,
    "avg_revenue": 266.1
  },
  {
    "day": "Thursday",
    "orders": 300,
    "avg_revenue": 280.41
  },
  {
    "day": "Friday",
    "orders": 259,
    "avg_revenue": 244.69
  },
  {
    "day": "Saturday",
    "orders": 274,
    "avg_revenue": 270.23
  },
  {
    "day": "Sunday",
    "orders": 286,
    "avg_revenue": 282.92
  }
];

export const recentOrders = [
  {
    "id": "ORD-250026",
    "date": "2025-12-28",
    "customer": "Harper Cooper",
    "country": "Japan",
    "region": "Asia Pacific",
    "product": "Horizon 4K Action Camera",
    "category": "Electronics",
    "quantity": 2,
    "total_sales": 658.0,
    "profit": 125.59,
    "discount_percent": 0.0,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250767",
    "date": "2025-12-28",
    "customer": "Daniel Rodriguez",
    "country": "Chile",
    "region": "Latin America",
    "product": "Coastline Linen Shirt",
    "category": "Clothing",
    "quantity": 2,
    "total_sales": 128.0,
    "profit": 26.83,
    "discount_percent": 0.0,
    "payment_method": "Bank Transfer",
    "customer_segment": "Corporate"
  },
  {
    "id": "ORD-251210",
    "date": "2025-12-28",
    "customer": "Emily Baker",
    "country": "China",
    "region": "Asia Pacific",
    "product": "Olive Wood Cutting Board",
    "category": "Home & Kitchen",
    "quantity": 5,
    "total_sales": 156.23,
    "profit": 27.43,
    "discount_percent": 8.1,
    "payment_method": "Credit Card",
    "customer_segment": "Home Office"
  },
  {
    "id": "ORD-251615",
    "date": "2025-12-28",
    "customer": "James Cooper",
    "country": "Canada",
    "region": "North America",
    "product": "Lumina Smart LED Lamp",
    "category": "Electronics",
    "quantity": 1,
    "total_sales": 69.76,
    "profit": -9.93,
    "discount_percent": 22.4,
    "payment_method": "Credit Card",
    "customer_segment": "Corporate"
  },
  {
    "id": "ORD-250197",
    "date": "2025-12-27",
    "customer": "Scarlett Carter",
    "country": "Canada",
    "region": "North America",
    "product": "Sapiens: A Brief History",
    "category": "Books",
    "quantity": 3,
    "total_sales": 65.0,
    "profit": 19.44,
    "discount_percent": 3.7,
    "payment_method": "Bank Transfer",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250693",
    "date": "2025-12-27",
    "customer": "Noah Adams",
    "country": "Canada",
    "region": "North America",
    "product": "Vertex Stainless Smartwatch",
    "category": "Electronics",
    "quantity": 1,
    "total_sales": 200.2,
    "profit": -9.75,
    "discount_percent": 19.6,
    "payment_method": "PayPal",
    "customer_segment": "Home Office"
  },
  {
    "id": "ORD-251391",
    "date": "2025-12-27",
    "customer": "Emily Young",
    "country": "Mexico",
    "region": "North America",
    "product": "Cascade Insulated Bottle",
    "category": "Home & Kitchen",
    "quantity": 3,
    "total_sales": 119.7,
    "profit": 23.78,
    "discount_percent": 0.0,
    "payment_method": "Credit Card",
    "customer_segment": "Home Office"
  },
  {
    "id": "ORD-251909",
    "date": "2025-12-27",
    "customer": "Daniel Hill",
    "country": "Brazil",
    "region": "Latin America",
    "product": "Coastline Linen Shirt",
    "category": "Clothing",
    "quantity": 1,
    "total_sales": 61.06,
    "profit": -1.79,
    "discount_percent": 4.6,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250549",
    "date": "2025-12-26",
    "customer": "Scarlett Mitchell",
    "country": "China",
    "region": "Asia Pacific",
    "product": "Summit Trekking Backpack",
    "category": "Clothing",
    "quantity": 2,
    "total_sales": 249.0,
    "profit": 86.47,
    "discount_percent": 0.0,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251398",
    "date": "2025-12-26",
    "customer": "Henry Hill",
    "country": "United States",
    "region": "North America",
    "product": "Aurora Wireless Earbuds Pro",
    "category": "Electronics",
    "quantity": 1,
    "total_sales": 188.45,
    "profit": 16.97,
    "discount_percent": 5.3,
    "payment_method": "Bank Transfer",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251735",
    "date": "2025-12-26",
    "customer": "Jackson King",
    "country": "Australia",
    "region": "Asia Pacific",
    "product": "Vortex Running Shoes",
    "category": "Clothing",
    "quantity": 1,
    "total_sales": 103.11,
    "profit": 21.77,
    "discount_percent": 5.4,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250892",
    "date": "2025-12-25",
    "customer": "Joseph Mitchell",
    "country": "Singapore",
    "region": "Asia Pacific",
    "product": "Alpine Down Jacket",
    "category": "Clothing",
    "quantity": 1,
    "total_sales": 272.53,
    "profit": 82.11,
    "discount_percent": 5.7,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251730",
    "date": "2025-12-25",
    "customer": "Harper Scott",
    "country": "Mexico",
    "region": "North America",
    "product": "Horizon 4K Action Camera",
    "category": "Electronics",
    "quantity": 4,
    "total_sales": 1263.36,
    "profit": 225.56,
    "discount_percent": 4.0,
    "payment_method": "PayPal",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251316",
    "date": "2025-12-24",
    "customer": "Abigail Nelson",
    "country": "South Africa",
    "region": "Middle East & Africa",
    "product": "Pulse Fitness Tracker X",
    "category": "Electronics",
    "quantity": 4,
    "total_sales": 529.15,
    "profit": 6.17,
    "discount_percent": 16.8,
    "payment_method": "Credit Card",
    "customer_segment": "Corporate"
  },
  {
    "id": "ORD-251372",
    "date": "2025-12-24",
    "customer": "Olivia Flores",
    "country": "Canada",
    "region": "North America",
    "product": "Lumina Smart LED Lamp",
    "category": "Electronics",
    "quantity": 1,
    "total_sales": 72.73,
    "profit": -8.64,
    "discount_percent": 19.1,
    "payment_method": "Debit Card",
    "customer_segment": "Home Office"
  },
  {
    "id": "ORD-250479",
    "date": "2025-12-23",
    "customer": "Victoria Rodriguez",
    "country": "Singapore",
    "region": "Asia Pacific",
    "product": "Cozy Weighted Blanket",
    "category": "Home & Kitchen",
    "quantity": 2,
    "total_sales": 238.0,
    "profit": 61.84,
    "discount_percent": 0.0,
    "payment_method": "Credit Card",
    "customer_segment": "Corporate"
  },
  {
    "id": "ORD-250734",
    "date": "2025-12-23",
    "customer": "Logan Scott",
    "country": "Australia",
    "region": "Asia Pacific",
    "product": "Vertex Stainless Smartwatch",
    "category": "Electronics",
    "quantity": 3,
    "total_sales": 667.82,
    "profit": 67.3,
    "discount_percent": 10.6,
    "payment_method": "Bank Transfer",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250520",
    "date": "2025-12-22",
    "customer": "Abigail Mitchell",
    "country": "United Arab Emirates",
    "region": "Middle East & Africa",
    "product": "Lumina Smart LED Lamp",
    "category": "Electronics",
    "quantity": 2,
    "total_sales": 169.73,
    "profit": -3.85,
    "discount_percent": 5.6,
    "payment_method": "PayPal",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251314",
    "date": "2025-12-22",
    "customer": "Ella Lopez",
    "country": "Mexico",
    "region": "North America",
    "product": "Olive Wood Cutting Board",
    "category": "Home & Kitchen",
    "quantity": 2,
    "total_sales": 62.76,
    "profit": 7.14,
    "discount_percent": 7.7,
    "payment_method": "Bank Transfer",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251399",
    "date": "2025-12-22",
    "customer": "Scarlett Lee",
    "country": "Germany",
    "region": "Europe",
    "product": "Lumen Aroma Diffuser",
    "category": "Home & Kitchen",
    "quantity": 2,
    "total_sales": 80.09,
    "profit": -0.15,
    "discount_percent": 19.1,
    "payment_method": "Bank Transfer",
    "customer_segment": "Corporate"
  },
  {
    "id": "ORD-251411",
    "date": "2025-12-22",
    "customer": "Daniel Adams",
    "country": "Netherlands",
    "region": "Europe",
    "product": "Cascade Insulated Bottle",
    "category": "Home & Kitchen",
    "quantity": 1,
    "total_sales": 37.94,
    "profit": -2.7,
    "discount_percent": 4.9,
    "payment_method": "Debit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251882",
    "date": "2025-12-21",
    "customer": "Olivia Cooper",
    "country": "United Kingdom",
    "region": "Europe",
    "product": "Horizon 4K Action Camera",
    "category": "Electronics",
    "quantity": 3,
    "total_sales": 877.44,
    "profit": 92.73,
    "discount_percent": 11.1,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-251977",
    "date": "2025-12-21",
    "customer": "Scarlett Allen",
    "country": "Canada",
    "region": "North America",
    "product": "Studio Yoga Leggings",
    "category": "Clothing",
    "quantity": 3,
    "total_sales": 158.24,
    "profit": 42.4,
    "discount_percent": 10.6,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250385",
    "date": "2025-12-20",
    "customer": "Amelia Adams",
    "country": "Netherlands",
    "region": "Europe",
    "product": "Nimbus Memory Foam Pillow",
    "category": "Home & Kitchen",
    "quantity": 2,
    "total_sales": 127.23,
    "profit": 21.98,
    "discount_percent": 0.6,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  },
  {
    "id": "ORD-250555",
    "date": "2025-12-19",
    "customer": "Amelia Young",
    "country": "Netherlands",
    "region": "Europe",
    "product": "Studio Yoga Leggings",
    "category": "Clothing",
    "quantity": 1,
    "total_sales": 51.8,
    "profit": 0.2,
    "discount_percent": 12.2,
    "payment_method": "Credit Card",
    "customer_segment": "Consumer"
  }
];

export const categoryList = [
  "Electronics",
  "Clothing",
  "Home & Kitchen",
  "Books"
];

export const segmentList = [
  "Consumer",
  "Corporate",
  "Home Office"
];

export const regionList = [
  "North America",
  "Europe",
  "Asia Pacific",
  "Latin America",
  "Middle East & Africa"
];

// Formatters
export const formatCurrency = (value: number, compact = false) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    notation: compact ? 'compact' : 'standard',
    maximumFractionDigits: compact ? 1 : 0,
  }).format(value);

export const formatNumber = (value: number, compact = false) =>
  new Intl.NumberFormat('en-US', {
    notation: compact ? 'compact' : 'standard',
    maximumFractionDigits: 1,
  }).format(value);

export const calcChange = (current: number, previous: number) => {
  if (previous === 0) return 0;
  return ((current - previous) / previous) * 100;
};
